fix: sonar run

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -154,9 +154,19 @@ jobs:
       - name: Sonar Analysis
         # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
         env:
+          # Needed to get PR information
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
-          EIRCTL_CONTAINER_ARG="-u $(id -u):$(id -g)" go run cmd/main.go run pipeline sonar:scan -- -Dsonar.scm.revision=${{ github.sha }}
+          mkdir -p ${PWD}/.scannerwork
+          chmod 0777 -R ${PWD}/.scannerwork
+          cp "$GITHUB_EVENT_PATH" .github/sonar-event.json
+          echo "current user: $(id -u):$(id -g)"
+          GITHUB_EVENT_PATH=/eirctl/.github/sonar-event.json \
+            go run cmd/main.go run pipeline sonar:scan -- -Dsonar.scm.revision=${{ github.sha }} \
+            -Dsonar.projectVersion=${{ needs.set-version.outputs.semVer }} \
+            -Dsonar.scm.provider=git \
+            -Dsonar.working.directory=/eirctl/.scannerwork || echo ".scannerwork failed to delete - unimportant in GHA runner"
 
   sonarcloud:
     name: SonarCloud analysis
